version: '3'

services:
  django:
    build: .
    environment:
      - ENV_FILE=.env
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6.2

  worker:
    env_file:
      - .env
    build: .
    command: celery -A settings worker -l info -Q light_queue
    volumes:
      - .:/code
    depends_on:
      - redis
