# Generated by Django 6.0.2 on 2026-03-16 12:06

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField(default=shortener.models.default_expiration)),
                ('original_link', models.CharField(max_length=200)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
