# Generated by Django 6.0.2 on 2026-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='shorted_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
