# Generated by Django 6.0.2 on 2026-03-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortlink_shorted_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='expires_at',
            new_name='surl_expires_at',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='surl_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
