# Generated by Django 6.0.2 on 2026-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_expires_at_shortlink_surl_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='surl_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
